<?php

/**
 * @file
 * Feeds HTTPFetcher Append Headers - basic API functions and hook implementations.
 */

/**
 * Implements hook_feeds_plugins().
 */
function feeds_httpfetcher_append_headers_feeds_plugins() {
  $path = backdrop_get_path('module', 'feeds_httpfetcher_append_headers');
  $info = array();
  $info['FeedsHTTPFetcherAppendHeaders'] = array(
    'name'        => t('Append Headers HTTP Fetcher'),
    'description' => t('HTTPFetcher with support for appending request headers.'),
    'handler' => array(
      'parent' => 'FeedsHTTPFetcher',
      'class'  => 'FeedsHTTPFetcherAppendHeaders',
      'file'   => 'plugins/FeedsHTTPFetcherAppendHeaders.inc',
      'path'   => $path,
    ),
  );
  return $info;
}

/**
 * Implements hook_autoload_info().
 */
function feeds_httpfetcher_append_headers_autoload_info() {
  return array(
    'FeedsHTTPFetcherAppendHeaders' => 'plugins/FeedsHTTPFetcherAppendHeaders.inc',
    'FeedsHTTPFetcherAppendHeadersResult' => 'plugins/FeedsHTTPFetcherAppendHeaders.inc',
  );
}
